# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Course.create(name: "Penmar Golf Course", location: "Venice, CA", par: 33, holes: 9, length: 2496, description: "Not far from Venice, Penmar Golf Course offers terrific views and challenging play for golfers at every skill level. Well-groomed fairways and greens keep Penmar Golf Course difficult yet friendly, and the staff can offer tips and tricks for playing your best round. Penmar Golf Course is a terrific choice for your regular rounds of golf or a new destination for you and friends when visiting Venice.", img: "https://exddilid.cdn.imgeng.in/app/courses/image/preview/34467.jpg")
Course.create(name: "Rancho Park Golf Course", location: "Los Angeles, CA", par: 71, holes: 18, length: 6630, description: "Designed in 1947, by William P Bell and William H. Johnson, Rancho Park is a par 71 championship golf course playing at a deceptive 6,630 yards. It is an undulating and challenging track that requires a great deal of skill and finesse. It is a course for purists, and virtually all of the legends have played Rancho at one point in their career. Set in the heart of Los Angeles, Rancho has been the home to numerous LA Opens, the PGA Senior Open and multiple LPGA tour events.", img: "https://exddilid.cdn.imgeng.in/app/courses/image/preview/91467.jpg")
Course.create(name: "Westchester Golf Course", location: "Los Angeles, CA", par: 64, holes: 18, length: 4339, description: "Welcome to Westchester Golf Course Conveniently located just north of LAX, near popular Westside beaches and communities, this 18-hole, 4,364 yard public golf course is a fun and affordable challenge for golfers of all abilities. The course has a casual feel to it, with impeccable greens, nighttime play, a world-class short game practice area, and a very popular Driving Range open to 10pm nightly. Perfect for scheduled play or spontaneous practice – Westchester Golf Course delivers great golf, every time.", img: "https://exddilid.cdn.imgeng.in/app/courses/image/preview/14701.jpg")
Course.create(name: "Encino Golf Course", location: "Encino, CA", par: 72, holes: 18, length: 7023, description: "Encino Golf Course is one of two courses that comprise the Sepulveda Golf Complex. Encino is a long and wide golf course, a nice test for the long hitter. With an open design, it is ideal for mid to high handicap golfers wanting to hone their game. The course was designed by William P. Bell & Sons and opened in 1957.", img: "https://exddilid.cdn.imgeng.in/app/courses/image/preview/91376.jpg")
Course.create(name: "Balboa Golf Course", location: "Encino, CA", par: 72, holes: 18, length: 6619, description: "Balboa Golf Course is one of two courses that comprise the Sepulveda Golf Complex. Balboa is challenging for the mid to high handicapper, with narrow tree-line fairways to test your game and shot-making avility. The course was Designed by William P. Bell & Sons and opened in 1954 as the Seulveda North Course.", img: "https://exddilid.cdn.imgeng.in/app/courses/image/preview/91373.jpg")
Course.create(name: "Chester Washington Golf Course", location: "Los Angeles, CA", par: 70, holes: 18, length: 6348, description: "Wonderful mature trees line the rolling fairways and include fun undulating greens on this 6321 yard par 70 golf course. Bent & Poa Annua greens with Kukuyu tees and fairways make for great conditions.", img: "https://exddilid.cdn.imgeng.in/app/courses/image/preview/104052.jpg")
Course.create(name: "Roosevelt Golf Course", location: "Los Angeles, CA", par: 33, holes: 9, length: 2478, description: "Roosevelt is an exciting 9 hole executive course located at the Roosevelt Municipal Golf Course facility in Los Angeles, CA. From the longest tees it presents 2,478 yards of golf for a par of 33. The course rating is 62.6 with a slope rating of 110. The course contact is Jerry Baxter, General Manager.", img: "https://exddilid.cdn.imgeng.in/app/courses/image/preview/14699.jpg")
Course.create(name: "Los Amigos Golf Course", location: "Downey, CA", par: 71, holes: 18, length: 6212, description: "Not far from Downey, Los Amigos Golf Course offers terrific views and challenging play for golfers at every skill level. Well-groomed fairways and greens keep Los Amigos Golf Course difficult yet friendly, and the staff can offer tips and tricks for playing your best round. Los Amigos Golf Course is a terrific choice for your regular rounds of golf or a new destination for you and friends when visiting Downey.", img: "https://exddilid.cdn.imgeng.in/app/courses/image/preview/104055.jpg")
Course.create(name: "Los Robles Greens Golf Course", location: "Thousand Oaks, CA", par: 70, holes: 18, length: 6137, description: "The picturesque Los Robles Greens Golf Course basks in the foothills of the beautiful, mountain-lined Conejo Valley. Situated in Thousand Oaks, just 39 miles from Los Angeles, the redesigned 6,274 yard, par 70 course lies twelve miles inland and 900 feet above sea level. Known for the giant oak trees that line its fairways and guard many of its undulating greens, Los Robles continues to be a public course in a private course setting.", img: "https://exddilid.cdn.imgeng.in/app/courses/image/preview/76413.jpg")
Course.create(name: "Alhambra Golf Course", location: "Alhambra, CA", par: 71, holes: 18, length: 5478, description: "If you're looking for a fun course and classic design that won't beat you up, Alhambra Golf Course is a great choice. This William F. Bell designed par-71 layout is only 5,478 yards from the back tees, so you don't have to be a long hitter to have success here. Three other sets of the tees on the course, which opened in 1956, mean it's friendly for seniors, juniors and shorter hitters as well.", img: "https://exddilid.cdn.imgeng.in/app/courses/image/preview/57425.jpg")
Course.create(name: "Brookside Golf Club", location: "Pasadena, CA", par: 72, holes: 18, length: 7104, description: "Brookside Golf Club, reminiscent of an earlier era, is steeped in 75 years of golf tradition. Designed by famed golf architect William P. Bell, Brookside Golf Club's 36 holes are nestled in the golden foothills of Pasadena next to the world famous Rose Bowl. The golf courses at Brookside have hosted many major championships including the Los Angeles Open and the National Public Links Championship. Experience Tradition. Experience Brookside Golf Club today. This course is located adjacent to the Rose Bowl and is the best course close to USC. There are 2 full courses to choose from and both are usually kept in excellent shape. The greens here are usually in superb condition and some of them can seem impossible due to tricky pin placements. There are plenty of big trees on the course to cause problems, and water will come into play on a couple of the holes.", img: "https://exddilid.cdn.imgeng.in/app/courses/image/preview/91453.jpg")

